branch-defaults:
  default:
    environment: Storefront-env
environment-defaults:
  Storefront-env:
    branch: null
    repository: null
global:
  application_name: Storefront
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
option_settings:
  aws:elb:listener:443:
    SSLCertificateId: arn:aws:acm:ap-southeast-1:887421295499:certificate/fc862a0b-84dc-48b5-aba5-6814f4a9da42
    ListenerProtocol: HTTPS
    InstancePort: 80
