branch-defaults:
  default:
    environment: Storefront-env
environment-defaults:
  Storefront-env:
    branch: null
    repository: null
global:
  application_name: Storefront
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
